// JWT token 
const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjk5NWNjMC03MGQ5LTQxYmMtOGI4MS03NGU1YjllNmFjZWQiLCJuYW1lIjoiZGFuYXIgbmloIGJvcyIsImV4cCI6MTczMzIxMDA5Mn0.GlItRDUMIa7tYjAUDeJHXUIRstljm0KvweBq_5iZH9I';

export default token;